spring:
  application:
    name: network-workflow-builder
  
  # Thymeleaf configuration
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    suffix: .html
    cache: false
    
  # Database configuration (H2 for development)
  datasource:
    url: jdbc:h2:mem:workflow
    driverClassName: org.h2.Driver
    username: sa
    password: password
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        
  # Web configuration
  web:
    resources:
      cache:
        period: 0
        
  # WebSocket configuration
  websocket:
    message-size-limit: 1024
    send-buffer-size-limit: 1024
    
  # JSON configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    
# Logging configuration
logging:
  level:
    com.networkflow: DEBUG
    org.springframework.web: INFO
    org.springframework.websocket: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/workflow-builder.log
    
# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      
# Application specific configuration
workflow:
  execution:
    thread-pool-size: 5
    timeout-seconds: 300
  python:
    executable: python
    script-path: python/netmiko_executor.py
  templates:
    directory: templates
    auto-load: true
  storage:
    type: file # or database
    backup-enabled: true
    
# WebJars configuration
webjars:
  locator-cache:
    enabled: true

networkflow:
  execution:
    thread-pool-size: 5
  python:
    executable: python
    script-path: python/netmiko_executor.py
  template:
    directory: templates/
  storage:
    type: file # or database
  
  # Generic Output Success Verification Configuration
  verification:
    # Global success indicators (case-insensitive)
    success-patterns:
      - "success"
      - "successful" 
      - "ok"
      - "up"
      - "active"
      - "operational"
      - "enabled" 
      - "configured"
      - "applied"
      - "completed"
      - "established"
      - "connected"
      - "reachable"
      - "online"
      - "ready"
      - "valid"
      - "accepted"
      - "building configuration"
      - "[ok]"
      - "saved"
      
    # Global failure indicators (case-insensitive)  
    failure-patterns:
      - "error"
      - "failed"
      - "failure"
      - "down"
      - "inactive"
      - "disabled"
      - "unreachable"
      - "timeout"
      - "invalid"
      - "rejected"
      - "denied"
      - "not found"
      - "not configured"
      - "not reachable"
      - "connection refused"
      - "authentication failed"
      - "command not found"
      - "syntax error"
      - "% invalid"
      - "% incomplete"
      - "% ambiguous command"
      - "% unknown command"
      - "login incorrect"
      - "access denied"
      - "connection timed out"
      - "no route to host"
      - "configuration error"
      - "invalid input"
      - "device not found"
      - "no such interface"
      - "vlan does not exist"
      
    # Context-specific patterns
    contexts:
      vlan:
        success-patterns:
          - "vlan.*active"
          - "switchport access vlan"
          - "vlan database"
        failure-patterns:
          - "vlan.*not.*found"
          - "invalid vlan"
          
      interface:
        success-patterns:
          - "line protocol is up"
          - "interface.*up.*up"
          - "switchport mode"
        failure-patterns:
          - "interface.*down"
          - "no such interface"
          
      ping:
        success-patterns:
          - "reply from"
          - "64 bytes from"
          - "ping statistics"
          - "\\d+\\s+packets.*\\d+\\s+received.*0%\\s+packet\\s+loss"
        failure-patterns:
          - "destination host unreachable"
          - "request timed out"
          - "100% packet loss"
          - "ping: cannot resolve"
          
      routing:
        success-patterns:
          - "connected.*via"
          - "\\d+\\.\\d+\\.\\d+\\.\\d+/\\d+"
        failure-patterns:
          - "no route"
          - "routing table empty"